services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "coeurcy"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Coeurcy}{boss|@88"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n-n8n_public.onrender.com"