services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "coeurcy"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "motdepassefort"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://ton-service.onrender.com"